version: '3.9'

services:
  apollo-launch-agent:
    container_name: ApolloLaunchAgent
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./agent.py:/agent.py
    ports:
      - "50051:50051"
    environment:
      - DOCKER_REGISTRY_USERNAME=${DOCKER_REGISTRY_USERNAME}
      - DOCKER_REGISTRY_TOKEN=${DOCKER_REGISTRY_TOKEN}
      - DOCKER_REGISTRY_URL=${DOCKER_REGISTRY_URL}