version: '3.9'

services:
  apollo-launch-agent:
    container_name: ApolloLaunchAgent
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./agent.py:/agent.py
    ports:
      - "50051:50051"